<?php

namespace UserBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findsalarie(){
        $q=$this->getEntityManager()
            ->createQuery("select u from UserBundle:User u WHERE u.salarie='1' ");
        return $q->getResult();
    }
}
