profilehomepage:
    path:     /profilehomepage
    defaults: { _controller: ProfilingBundle:Profile:index_profile }
album:
    path:     /album
    defaults: { _controller: ProfilingBundle:Profile:album }
createPost:
    path:     /post/create
    defaults: { _controller: ProfilingBundle:Profile:create }
showPost:
    path:     /post/read
    defaults: { _controller: ProfilingBundle:Profile:read }
updatePost:
    path:     /post/update/{idp}
    defaults: { _controller: ProfilingBundle:Profile:update }
tag:
    resource: "@ProfilingBundle/Controller/"
    type: annotation
paramInfo:
    path:     /parametres
    defaults: { _controller: ProfilingBundle:Profile:paramInfo }
autreprofile:
    path:     /autre/{id}
    defaults: { _controller: ProfilingBundle:Profile:autreprofile }
autrealbum:
    path:     /autrealbum/{id}
    defaults: { _controller: ProfilingBundle:Profile:autrealbum }
photoProfil:
    path:     /photoProfil
    defaults: { _controller: ProfilingBundle:Profile:updatepic }
ChangePassword:
    path:     /changepassword
    defaults: { _controller: fos_user.change_password.controller:changePasswordAction }
DemandeSalarie:
    path:     /demandesalarie
    defaults: { _controller: ProfilingBundle:Profile:demandesalarie }
AfficherDemandeSalarie:
    path:     /admin/afficherdemandesalarie
    defaults: { _controller: ProfilingBundle:Profile:AfficherDemandeSalarie }
TraiterDemande:
    path:     /admin/traiterdemande/{id}
    defaults: { _controller: ProfilingBundle:Profile:traiterdemande }
RefuserDemande:
    path:     /admin/refuserdemande/{idd}
    defaults: { _controller: ProfilingBundle:Profile:RefuserDemande }
AfficherSalarie:
    path:     /admin/salaries/{idu}/{idd}
    defaults: { _controller: ProfilingBundle:Profile:AfficherSalarie }
AfficherS:
    path:     /admin/listeSa
    defaults: { _controller: ProfilingBundle:Profile:AfficherSa }
GererSalarier:
    path:     /admin/gerersalarier/{id}
    defaults: { _controller: ProfilingBundle:Profile:GererSalarier }
AjouterCommentaire:
    path:     /ajoutercommentaire/{idp}/{idu}
    defaults: { _controller: ProfilingBundle:Profile:PosterCommentaire }